### PR TITLE
More cleanup and models

### PR DESCRIPTION
**Pull request by IEvangelist**

### CODE REVIEW

**Comment by bradygaster** [comment]
HUGE! thanks dude!

**Comment by timheuer** [comment]
@IEvangelist why not use the AOAI SDK for the model types (assuming you're just have them here for serialization purposes)?

**Comment by IEvangelist** [comment]
> @IEvangelist why not use the AOAI SDK for the model types (assuming you're just have them here for serialization purposes)?

@timheuer - The AOAI SDK models are only a part of it, the AI Chat Protocol APIs have a different spec and these models are a 1:1 with that spec. The AOAI models are subject to change, this kind of helps to ensure that we don't break between SDK updates, since we'll control the mapping logic. Does that make sense?

**Comment by timheuer** [comment]
Makes sense. Generally I've found that not all types were needed to be in the 'wire' format, but the ChatMessage/Choices, etc. do.  I've used this: https://github.com/timheuer/dotnet-streaming-api/tree/main/src/SharedChatTypes

**Pull request merged**
